openapi: 3.0.3
info:
  title: Dokumen API Cloud Function - OpenAPI 3.0
  description: >-
    Jelaskan disini apa saja yang perlu dijelaskan
    termasuk informasi yang diperlukan untuk dinilai
    term of service isi dari link repo dari swagger ini
  termsOfService: https://github.com/PhilanderNews/swagger
  contact:
    email: befousmain@gmail.com
  license:
    name: Peda Package
    url: https://pkg.go.dev/github.com/PhilanderNews/Backend
  version: 1.0.3
externalDocs:
  description: Repo GCF
  url: https://github.com/PhilanderNews/gcf/
servers:
  - url: https://asia-southeast2-befous.cloudfunctions.net/PhilanderNews
tags:
  - name: Authorization
    description: Membuat akun, login, authorization
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/get/ #yang ini blom diganti ====================================================================
  - name: User
    description: CRUD collection user
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/post/ #yang ini blom diganti ====================================================================
  - name: Berita
    description: CRUD collection berita
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/post/ #yang ini blom diganti ====================================================================
  - name: Komentar
    description: CRUD collection komentar
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/post/ #yang ini blom diganti ====================================================================
paths:
# ------------------------- Authorization
  /GenerateVerifikasi:
    post:
      tags:
        - Authorization
      summary: GenerateVerifikasi
      description: Generate kode verifikasi
      operationId: GenerateKode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatGenerateVerifikasi'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /Registrasi:
    post:
      tags:
        - Authorization
      summary: Registrasi
      description: Membuat akun user dengan password terenkripsi
      operationId: MembuatUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /Login:
    post:
      tags:
        - Authorization
      summary: Login
      description: Masukkan username dan password yang telah didaftarkan
      operationId: MembuatTokenUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatLoginUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilDapetToken'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /TokenValue:
    get:
      tags:
        - Authorization
      summary: Authorization
      description: Authorization
      operationId: Authorization
      requestBody:
        content:
          application/json:
      responses:
        '200':
          description: Successful decoding of the token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulDecodeAuthorization'
        '400':
          description: Failed decoding of the token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedDecodeAuthorization'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey

# ------------------------- User

  /AmbilSatuUser:
    post:
      tags:
        - User
      summary: Ambil Satu Pengguna
      description: Mengambil informasi satu pengguna berdasarkan username
      operationId: AmbilSatuUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatUsernameUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetOneUser'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /AmbilSemuaUser:
    get:
      tags:
        - User
      summary: Ambil Semua Pengguna
      description: Mengambil informasi semua pengguna
      operationId: AmbilSemuaUser
      requestBody:
        content:
          application/json:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetAllUser'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /EditUser:
    put:
      tags:
        - User
      summary: Perbarui Pengguna
      description: Memperbarui informasi pengguna berdasarkan data yang diberikan
      operationId: UpdateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /HapusUser:
    delete:
      tags:
        - User
      summary: Hapus Pengguna
      description: Menghapus informasi pengguna berdasarkan username
      operationId: HapusUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatUsernameUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey

# ------------------------- Berita

  /TambahBerita:
    post:
      tags:
        - Berita
      summary: Tambah Berita
      description: Menambahkan berita baru ke dalam mongodb
      operationId: TambahBerita
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatBerita'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /AmbilSatuBerita:
    post:
      tags:
        - Berita
      summary: Ambil Satu Berita
      description: Mengambil informasi satu berita berdasarkan ID
      operationId: AmbilSatuBerita
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatIDBerita'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetOneBerita'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /AmbilSemuaBerita:
    get:
      tags:
        - Berita
      summary: Ambil Semua Berita
      description: Mengambil informasi semua berita
      operationId: AmbilSemuaBerita
      requestBody:
        content:
          application/json:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetAllBerita'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /EditBerita:
    put:
      tags:
        - Berita
      summary: Perbarui Berita
      description: Memperbarui informasi berita berdasarkan data yang diberikan
      operationId: UpdateBerita
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatBerita'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /HapusBerita:
    delete:
      tags:
        - Berita
      summary: Hapus Berita
      description: Menghapus informasi berita berdasarkan ID
      operationId: HapusBerita
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatIDBerita'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey

# ------------------------- Komentar

  /TambahKomentar:
    post:
      tags:
        - Komentar
      summary: Tambah Komentar
      description: Menambahkan komentar baru ke dalam sistem
      operationId: TambahKomentar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatKomentar'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /AmbilSatuKomentar:
    post:
      tags:
        - Komentar
      summary: Ambil Satu Komentar
      description: Mengambil informasi satu komentar berdasarkan ID
      operationId: AmbilSatuKomentar
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatIDKomentar'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetOneKomentar'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /AmbilSemuaKomentar:
    get:
      tags:
        - Komentar
      summary: Ambil Semua Komentar
      description: Mengambil informasi semua komentar
      operationId: AmbilSemuaKomentar
      requestBody:
        content:
          application/json:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilGetAllKomentar'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /EditKomentar:
    put:
      tags:
        - Komentar
      summary: Perbarui Komentar
      description: Memperbarui informasi komentar berdasarkan data yang diberikan
      operationId: UpdateKomentar
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatKomentarTanpaBerita'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey
  /HapusKomentar:
    delete:
      tags:
        - Komentar
      summary: Hapus Komentar
      description: Menghapus informasi komentar berdasarkan ID
      operationId: HapusKomentar
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FormatIDKomentar'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - Authorization:
            - write:apiKey
            - read:apiKey

components:
  schemas:
    # ----------------------------- Schema struct User
    FormatGenerateVerifikasi:
      example:
        nowa: "6281271720763"
        username: "contoh"
    # ----------------------------- Schema struct User
    FormatUser:
      example:
        name: "Contoh"
        email: "contoh@gmail.com"
        no_whatsapp: "6281271720763"
        username: "contoh"
        password: "contoh"
        role: "admin"
    FormatLoginUser:
      example:
        username: "contoh"
        password: "contoh"
    FormatUsernameUser:
      example:
        username: "contoh"
    # ----------------------------- Schema struct Berita
    FormatBerita:
      example:
        id: "contoh"
        kategori: "politic"
        judul: "contoh"
        preview: "ini adalah contoh politic"
        konten:
          paragraf1: "contoh"
          paragraf2: "contoh"
          paragraf3: "contoh"
          paragraf4: "contoh"
          paragraf5: "contoh"
          paragraf6: "contoh"
          paragraf7: "contoh"
          paragraf8: "contoh"
          paragraf9: "contoh"
          paragraf10: "contoh"
        sumber: "contoh.com"
        image: "google.com"
    FormatIDBerita:
      example:
        id: "contoh"
    # ----------------------------- Schema struct Komentar
    FormatKomentar:
      example:
        id: "contoh"
        id_berita: "contohberita"
        komentar: "ini adalah contoh komentar"
    FormatKomentarTanpaBerita:
      example:
        id: "contoh"
        komentar: "ini adalah contoh komentar"
    FormatIDKomentar:
      example:
        id: "contoh"
    # ----------------------------- Schema response
    BerhasilDapetToken:
      example:
        status: true
        message: "berhasil login"
        token: "v4.public.eyJleHAiOiIyMDIzLTExLTMwVDA4OjUwOjE2WiIsImlhdCI6IjIwMjMtMTEtMzBUMDY6NTA6MTZaIiwibmFtZSI6Iklicm9oaW0gTXViYXJvayIsIm5iZiI6IjIwMjMtMTEtMzBUMDY6NTA6MTZaIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJpYnJvaGltIn1438aT4CYjh1m4w1NLuW-ebGKL6mvztDPsh2ZKLy8DKBjKh4KZEI4ZQAboqKTLhGzQ930yKVAEMKSAvMHhqMQH"
    BerhasilGetAllUser:
      example:
        - name: "Contoh1"
          email: "contoh1@gmail.com"
          no_whatsapp: "6281271720763"
          username: "contoh1"
          password: "hashed password"
          role: "admin"
        - name: "Contoh2"
          email: "contoh2@gmail.com"
          no_whatsapp: "6281271720763"
          username: "contoh2"
          password: "hashed password"
          role: "author"
    BerhasilGetOneUser:
      example:
        name: "Contoh"
        email: "contoh@gmail.com"
        no_whatsapp: "6281271720763"
        username: "contoh"
        password: "hashed password"
        role: "admin"
    BerhasilGetAllBerita:
      example:
        - id: "contoh1"
          kategori: "politic"
          judul: "contoh1"
          preview: "ini adalah contoh politic"
          konten:
            paragraf1: "contoh1"
            paragraf2: "contoh1"
            paragraf3: "contoh1"
            paragraf4: "contoh1"
            paragraf5: "contoh1"
            paragraf6: "contoh1"
            paragraf7: "contoh1"
            paragraf8: "contoh1"
            paragraf9: "contoh1"
            paragraf10: "contoh1"
          penulis: "contoh1"
          sumber: "contoh1.com"
          image: "google.com"
          waktu: "Monday, 2 January 2006 15:04 WIB"
        - id: "contoh2"
          kategori: "politic"
          judul: "contoh2"
          preview: "ini adalah contoh politic"
          konten:
            paragraf1: "contoh2"
            paragraf2: "contoh2"
            paragraf3: "contoh2"
            paragraf4: "contoh2"
            paragraf5: "contoh2"
            paragraf6: "contoh2"
            paragraf7: "contoh2"
            paragraf8: "contoh2"
            paragraf9: "contoh2"
            paragraf10: "contoh2"
          penulis: "contoh2"
          sumber: "contoh2.com"
          image: "google.com"
          waktu: "Monday, 2 January 2006 15:04 WIB"
    BerhasilGetOneBerita:
      example:
        id: "contoh"
        kategori: "politic"
        judul: "contoh"
        preview: "ini adalah contoh politic"
        konten:
          paragraf1: "contoh"
          paragraf2: "contoh"
          paragraf3: "contoh"
          paragraf4: "contoh"
          paragraf5: "contoh"
          paragraf6: "contoh"
          paragraf7: "contoh"
          paragraf8: "contoh"
          paragraf9: "contoh"
          paragraf10: "contoh"
        penulis: "contoh"
        sumber: "contoh.com"
        image: "google.com"
        waktu: "Monday, 2 January 2006 15:04 WIB"
    BerhasilGetAllKomentar:
      example:
        - id: "contoh1"
          id_berita: "contohberita"
          name: "contoh1"
          tanggal: "January 2, 2006"
          komentar: "ini adalah contoh komentar"
        - id: "contoh2"
          id_berita: "contohberita"
          name: "contoh2"
          tanggal: "January 2, 2006"
          komentar: "ini adalah contoh komentar"
    BerhasilGetOneKomentar:
      example:
        id: "contoh"
        id_berita: "contohberita"
        name: "contoh"
        tanggal: "January 2, 2006"
        komentar: "ini adalah contoh komentar"
    Berhasil:
      example:
        status: true
        message: "petunjuk apa yang berhasil"
    Gagal:
      example:
        status: false
        message: "petunjuk dimana salahnya"
    SuccessfulDecodeAuthorization:
      example:
        status: true
        data:
          name: "ibrohim"
          no_whatsapp: ""
          username: "Ibrohim Mubarok"
          password: ""
          role: "admin"
        message: "berhasil decode token"
    FailedDecodeAuthorization:
      example:
        status: false
        data:
          no_whatsapp: ""
          username: ""
          password: ""
        message: "header login tidak ditemukan"
  requestBodies:
    AuthReq:
      description: Request Authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Auth'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AuthResponse'
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
